routes/web.php
<?php

use App\Http\Controllers\ItemController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::middleware('auth')->group(function () {
    Route::resource('items', ItemController::class);
    Route::get('overview', [ItemController::class, 'overview'])
        ->name('items.overview');
});

require __DIR__.'/auth.php';

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'name',
        'active',
        'type',
        'content'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'active' => 'boolean',
        'type' => 'integer',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ItemRequest;
use App\Models\Item;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ItemController extends Controller
{
    /**
     * Create the controller instance.
     *
     * @return void
     */
    public function __construct(Auth $auth)
    {
        $this->auth = $auth;

        $this->authorizeResource(Item::class, 'item');
    }


    /**
     * Display a page of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function overview(Request $request)
    {
        $this->authorize('overview');

        return view('item.overview', [
            'collection' =>
                Item::where('user_id', $this->auth::id())
                    ->orderByDesc('updated_at')
                    ->paginate(10, ['*'], 'page', $request->page)
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('item.overview', [
            'collection' =>
                Item::where('user_id', $this->auth::id())
                    ->orderByDesc('updated_at')
                    ->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('item.edit', [
            'item' => new Item(),
            'title' => __('Add Item'),
            'action' => route('items.store'),
            'method' => 'post',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ItemRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ItemRequest $request)
    {
        $data = $request->validated();

        $data = Item::create([
            'user_id' => 1,
            'name' => $data['name'],
            'active' => $data['active'],
            'type' => $data['type'],
            'content' => $data['content'],
        ]);

        return redirect(route('items.overview'))
            ->with('status', __('Item created!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('item.detail', [
            'item' => $item
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('item.edit', [
            'item' => $item,
            'title' => __('Edit Item'),
            'action' => route('items.update', ['item' => $item]),
            'method' => 'patch',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ItemRequest  $request
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(ItemRequest $request, Item $item)
    {
        $data = $request->safe()->only(
            ['name' ,'active', 'type', 'content']
        );

        $item->fill($data)->save();

        return redirect(route('items.show', [
            'item' => $item
        ]))->with('status', __('Item updated!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();

        return redirect(route('items.overview'))
            ->with('status', __('Item removed!'));;
    }
}

app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.base');
    }
}

resources/views/item/detail.blade.php
@push('css')
    <style>
        .detail__main {
            margin: 0 15% 4rem 15%;
        }
        .detail__heading {
            margin: 3rem 0 1rem 0;
            text-align: center;
        }
        .detail__type,
        .detail__active,
        .detail__body {
            margin-top: 1rem;
        }
        .detail__body {
            white-space: pre-wrap;
        }
    </style>
@endpush
<x-base-layout>
    <div class="detail">
        <x-header>
            <x-link
                :href="route('items.overview')"
                class="edit_index"
            >
                {{ __('Overview') }}
            </x-link>
        </x-header>
        <main class="detail__main">
            <h1 class="detail__heading">{{ $item->name }}</h1>
            <x-status class="detail__status" :status="session('status')" />
            <div class="detail__type"><strong>Type: {{ $item->type }}</strong></div>
            <div class="detail__active"><strong>Active: {{ $item->active ? 'true' : 'false' }}</strong></div>
            <p class="detail__body">{{ $item->content }}</p>
        </main>
        <x-footer class="detail__footer" />
    </div>
</x-base-layout>

resources/views/item/edit.blade.php
@push('css')
    <style>
        .edit__main {
            margin: 1rem;
        }
        .edit__box {
            min-width: 32rem;
            padding: 2rem 1rem;
        }
        .edit__title {
            text-align: center;
            margin: 1rem;
        }
        .edit__name,
        .edit__active,
        .edit__type,
        .edit__content,
        .edit__submit {
            display: block;
            width: 100%;
            margin-top: 1rem;
        }
        .login__active-input,
        .login__active-text {
            vertical-align: middle;
        }
        .edit__remove,
        .edit__button {
            width: 100%;
        }
        .edit__remove {
            margin-top: 1rem;
        }
    </style>
@endpush
<x-base-layout>
    <div class="edit">
        <x-header>
            <x-link
                :href="route('items.overview')"
                class="edit_index"
            >
                {{ __('Overview') }}
            </x-link>
        </x-header>
        <main class="index__main">
            <x-box class="edit__box">
                <h3 class="edit__title">{{ $title }}</h3>
                <x-status class="edit__status" :status="session('status')" />
                <x-errors class="edit__errors" :errors="$errors" />
                <form method="post" action="{{ $action }}" class="edit__form">
                    @method($method)
                    @csrf
                    <x-input type="text" name="name" id="name" class="edit__name" :placeholder="__('Name')" :value="old('name', $item['name'])" required autofocus />
                    <x-input type="number" name="type" id="type" class="edit__type" :placeholder="__('Type')" :value="old('type', $item['type'])" required />
                    <x-textarea name="content" id="content" class="edit__content" :placeholder="__('Content')">{{ old('content', $item['content']) }}</x-textarea>
                    <label for="active" class="edit__active">
                        <input type="checkbox" name="active" id="active" class="login__active-input" {{ old('active', $item['active']) ? 'checked="checked"' : '' }} />
                        <span class="login__active-text">{{ __('Active') }}</span>
                    </label>
                    <x-button type="submit" class="edit__submit button--blue">
                        {{ $title }}
                    </x-button>
                </form>
                @isset($item->id)
                    <form method="post" action="{{ route('items.destroy', ['item' => $item]) }}" class="edit__remove">
                        @method('delete')
                        @csrf
                        <x-button type="submit" class="edit__button button--red">
                            {{ __('Remove Item') }}
                        </x-button>
                    </form>
                @endisset
            </x-box>
        </main>
        <x-footer class="edit__footer" />
    </div>
</x-base-layout>

resources/views/item/overview.blade.php
@push('css')
    <style>
        .overview__main {
            margin: 0 10% 4rem 10%;
        }
        .overview__heading {
            margin: 3rem 0 1rem 0;
            text-align: center;
        }
        .overview__status {
            margin-bottom: 1rem;
        }
        .overview__pagination {
            margin-top: 1rem;
            text-align: right;
        }
    </style>
@endpush
<x-base-layout>
    <div class="overview">
        <x-header>
            <x-link
                :href="route('items.create')"
                class="index__link"
            >
                {{ __('New Item') }}
            </x-link>
        </x-header>
        <main class="overview__main">
            <h1 class="overview__heading">Collection</h1>
            <x-status class="overview__status" :status="session('status')" />
            <table class="table">
                <thead class="table__header">
                    <tr class="table__row table__row--heading">
                        <th class="table__heading">Id</th>
                        <th class="table__heading">Name</th>
                        <th class="table__heading">Active</th>
                        <th class="table__heading">Type</th>
                        <th class="table__heading">Actions</th>
                    </tr>
                </thead>
                <tbody class="table__body">
                    @foreach ($collection as $item)
                        <tr class="table__row table__row--data">
                            <td class="table__data">{{ $item->id }}</td>
                            <td class="table__data">{{ $item->name }}</td>
                            <td class="table__data">{{ $item->active ? 'true' : 'false' }}</td>
                            <td class="table__data">{{ $item->type }}</td>
                            <td class="table__data">
                                <x-link
                                    :href="route('items.show', ['item' => $item])"
                                    class="overview__show button-link--small button-link--light"
                                >
                                    {{ __('Show') }}
                                </x-link>
                                <x-link
                                    :href="route('items.edit', ['item' => $item])"
                                    class="overview__edit button-link--small button-link--blue"
                                >
                                    {{ __('Edit') }}
                                </x-link>
                                <form
                                    method="post"
                                    action="{{ route('items.destroy', ['item' => $item]) }}"
                                    class="overview__form"
                                    style="display:inline-block;"
                                >
                                    @method('delete')
                                    @csrf
                                    <x-button type="submit" class="overview__remove button--small button--red">
                                        {{ __('Remove') }}
                                    </x-button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @if($collection instanceof \Illuminate\Pagination\LengthAwarePaginator)
                <div class="overview__pagination">
                    @if($collection->previousPageUrl())
                        <x-link
                            :href="$collection->previousPageUrl()"
                            class="overview__next button-link--small button-link--dark"
                        >
                            {{ __('Previous') }}
                        </x-link>
                    @endif
                    @if($collection->nextPageUrl())
                        <x-link
                            :href="$collection->nextPageUrl()"
                            class="overview__next button-link--small button-link--dark"
                        >
                            {{ __('Next') }}
                        </x-link>
                    @endif
                </div>
            @endif
        </main>
        <x-footer class="overview__footer" />
    </div>
</x-base-layout>